--Es 1

--IMP(EMPNO, DEPTNO, ENAME, JOB, SAL)
--DIP(DEPTNO, DNAME, LOC, MINSAL, MAXSAL)

CREATE TRIGGER ACCOUNTING_TO_SALES
AFTER UPDATE OF DNAME ON DIP
FOR EACH ROW
WHEN(OLD.DNAME='ACCOUNTING' AND NEW.DNAME='SALES')
BEGIN
UPDATE IMP
SET NEW.SAL = OLD.SAL + 100
WHERE DEPTNO =: OLD.DEPTNO;
END;
/

--Es 2

--IMP(EMPNO, ENAME, JOB, SAL )
--SUMMARY(JOB, NUM )

--a)

CREATE TRIGGER INSERT_ON_IMP
AFTER INSERT ON IMP
FOR EACH ROW
DECLARE
N NUMBER;
BEGIN
SELECT COUNT(*) INTO N
FROM SUMMARY
WHERE JOB =: NEW.JOB;
IF(N=0) THEN
INSERT INTO SUMMARY (JOB, NUM)
VALUES(:NEW.JOB,1);
ELSE
UPDATE SUMMARY
SET NUM = NUM + 1
WHERE JOB =: NEW.JOB;
END IF;
END;
/

--b)

CREATE TRIGGER UPDATE_JOB_ON_IMP
AFTER UPDATE OF JOB ON IMP
FOR EACH ROW
DECLARE
N NUMBER;
M NUMBER;
BEGIN
--CASO ELIMINAZIONE JOB
SELECT COUNT(*) INTO N
FROM SUMMARY
WHERE JOB =:OLD.JOB;
IF(N>1) THEN --ho ancora impiegati per quel job
UPDATE SUMMARY
SET NUM = NUM - 1
WHERE JOB =: OLD.JOB;
ELSE --l'impiegato eliminato era l'ultimo per quel job
DELETE FROM SUMMARY
WHERE JOB =: OLD.JOB;
END IF;
--CASO INSERIMENTO JOB
SELECT COUNT(*) INTO M
FROM SUMMARY
WHERE JOB =: NEW.JOB;
IF(M=0) --non ho ancora impiegati registrati per quel job
INSERT INTO SUMMARY(JOB, NUM)
VALUES(:NEW.JOB, 1);
ELSE --ho gia qualcuno con quel job
UPDATE SUMMARY
SET NUM = NUM + 1
WHERE JOB =: NEW.JOB;
END IF;
END;
/